on:
  workflow_run:
    workflows: [release]
    types:
      - completed

name: choco
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: dawidd6/action-download-artifact@v2
      with:
        name: dist
        path: distecho
        run_id: ${{ github.event.workflow_run.id }}
    - name: hash
      run: | 
        shasum -a 256 dist/gitviz_windows_amd64.exe | head -c 40 >> ./choco/tools/LICENSE.txt

    - id: version
      run: echo "::set-output name=version::$(echo ${{ github.event.workflow_run.ref_name }} | cut -c -2)"

    - name: choco pack
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: pack ./choco/gitviz.nuspec --version ${{ steps.version.outputs.version }}

    - name: choco push
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: push --api-key=${{ secrets.CHOCOLATEY_APIKEY }}

