name: release
on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: build
        run: |
          go install github.com/mitchellh/gox@latest
          gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" -os "linux windows darwin" -arch "arm64 amd64 aarch64"

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
